kind: pipeline
type: kubernetes
name: build
metadata:
  namespace: drone
steps:
  - name: cert-manager-webhook-hetzner
    image: banzaicloud/drone-kaniko
    depends_on: ["clone"]
    resources:
      requests:
        cpu: 50
        memory: 250MiB
      limits:
        cpu: 2000
        memory: 1GiB
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_user
      password:
        from_secret: drone_pw
      registry: registry.idlerelaychat.de
      repo: cert-manager-webhook-hetzner
      tags:
        - latest
        - v0.0.3
---
kind: secret
name: docker_username
get:
  path: pipeline-secrets
  name: REGISTRY_USER
---
kind: secret
name: docker_password
get:
  path: pipeline-secrets
  name: REGISTRY_PASSWORD
