name: publish
on:
  push:
    branches: ['main']
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ko build
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
      - uses: ko-build/setup-ko@v0.6
      - run: ko build --bare .
